APP:
  CLEAR_LOG: false
  CUSTOM_CRON:
  SHORT_CRON: true
  LONG_CRON: false
  LANGUAGE: 
SENDER:
  EMAIL: example@mail.com
  EMAIL_PASSWORD: Password1234
  HOST: smtp.example.com
  PORT_EMAIL: 450
users:                                  # See README to configure users and servers
servers:
