APP:
  CLEAR_LOG: true
  CUSTOM_CRON: 
  SHORT_CRON: true
  LONG_CRON: false
SENDER:
  EMAIL: contact@mira-ceti.ovh
  EMAIL_PASSWORD: MailMira007
  HOST: smtp.example.com
  PORT_EMAIL: 465
users:                               # a list of users to be notified
- email: gaetan.patruno@gmail.com
- email: gaetan.pat@free.fr
servers:                             # A server list
- name: Server Demo
  host: demo.wireless-assist.ovh
  services:                         # A list of services to check from the server
  - name: Postgres  # Database 
    port: 5432
- name: Server Perso
  host: mira-ceti.ovh
  services:                         
  - name: openVPN  # openVPN 
    port: 
  - name: Minecraft  # openVPN 
    port: 25546
- name: Server DEV
  host: wireless-assist.ovh
