APP:
  CLEAR_LOG: false
  CUSTOM_CRON: null
  SHORT_CRON: true
  LONG_CRON: false
  LANGUAGE: 'EN'
SENDER:
  EMAIL: example@mail.com
  EMAIL_PASSWORD: Password1234
  HOST: smtp.example.com
  PORT_EMAIL: 450
users:                               # a list of users to be notified
- email: user.viewer@mail.com
- name: User 2                      # name is optionnal
  email: user2.viewer@mail.com
servers:                             # A server list
- name: Server Demo
  host: demo.domaine-name.com
  port: 22                          # port is optionnal, default port: 22
  services:                         # A list of services to check from the server
  - name: Postgres  # Database 
    port: 5432
  - name: API       # API 
    port: 3000
- name: Server Perso
  host: perso.checkserv.com
  services: 
  - name: OpenVPN
    port: 1194
    defaultstate: false             
- name: Server Web
  host: database.domaine.com
  port: 80
  defaultstate: false
