when:
  - event: push


steps:

  - name: get-version
    image: node:22
    commands:
      - echo "🔍 Extracting version from package.json..."
      - export APP_VERSION=(node -p -e "require('./package.json').version")
      - echo "Version extracted: $APP_VERSION"
      - echo ${APP_VERSION}
      - echo "APP_VERSION=$APP_VERSION" >> /woodpecker/env

  - name: audit
    image: node:22
    commands:
      - echo "🔒 Running security audit..."
      - npm i
      - npm audit --production

  - name: lint
    image: node:22
    commands:
      - echo "🔍 Running lint..."
      - npm run lint
    failure: ignore

  - name: node-build
    image: node:22
    commands:
      - echo "🛠 Building Node..."
      - npm run build --if-present
      
  - name: docker-build
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - echo "🛠 Building Docker image..."
      - docker build -t ${CI_REPO_NAME,}:${CI_COMMIT_BRANCH}-$APP_VERSION .
    
