when:
  - event: push
    
steps:
  - name: security-audit
    image: node:22
    commands:
      - echo "🔒 Running security audit..."
      - npm i
      - npm audit --production

  - name: lint
    image: node:22
    commands:
      - echo "🔍 Running lint..."
      - npm run lint

  - name: node-build
    image: node:22
    commands:
      - echo "🛠 Building Node..."
      - npm i
      - npm run build --if-present
      
  - name: docker-build
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - echo "🛠 Building Docker image..."
      - docker build -t ${CI_REPO_NAME,}:${CI_COMMIT_BRANCH} .
      
