when:
    branch: deploy
    event: push

steps:

  - name: docker-build
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: gpatruno/checkserv
      dockerfile: Dockerfile
      registry: docker.io
      tag: test
      dry-run: true
      output: type=oci,dest=${CI_REPO_OWNER}-test.tar

