when:
    branch: deploy
    event: push

# depends_on:
#   - build

# runs_on: [ success ]

steps:
  - name: docker-build
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - echo "🛠 Building Docker image..."
      - docker build -t ${CI_REPO_OWNER}/${CI_REPO_NAME,}:${CI_COMMIT_BRANCH} .
      - echo "🔑 Logging in to Docker Hub..."
      - echo $DOCKER_USERNAME
      - echo "$DOCKER_USERNAME"
      - echo ${DOCKER_USERNAME}
      - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin
      - echo "📤 Pushing Docker image to Docker Hub..."
      - echo "docker push " ${CI_REPO_OWNER}/${CI_REPO_NAME,}:${CI_COMMIT_BRANCH}
