when:
    branch: deploy
    event: push

steps:

  - name: docker-build
    image: plugins/docker
    settings:
      repo: gpatruno/checkserv
      dockerfile: Dockerfile
      registry: docker.io
      tag: next
      dry-run: true
      output: type=oci,dest=${CI_REPO_OWNER}-test.tar

