when:
    branch: deploy
    event: push

steps:
  - name: docker-build-and-push
    image: docker:24.0  # Utilise la dernière version stable de Docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Nécessaire pour interagir avec Docker
    settings:
      registry: docker.io
    commands:
      - echo "🛠 Building Docker image..."
      - docker build -t gpatruno/checkserv:next .
      - echo "🔑 Logging in to Docker Hub..."
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - echo "📤 Pushing Docker image to Docker Hub..."
      - docker push gpatruno/checkserv:next

