when:
    branch: deploy
    event: push

steps:
  - name: docker-build-and-push
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - echo "🛠 Building Docker image..."
      - docker build -t ${CI_REPO_OWNER}/${CI_REPO_NAME,}:${CI_COMMIT_BRANCH} .
      - echo "🔑 Logging in to Docker Hub..."
      - echo ${CI_REPO_NAME}
      - docker login -u "$DOCKER_USERNAME" --password-stdin
      - echo "📤 Pushing Docker image to Docker Hub..."
      - echo "docker push " ${CI_REPO_OWNER}/${CI_REPO_NAME,}:${CI_COMMIT_BRANCH}
